#Server config
server:
   compression:
      enabled: true
      mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      min-response-size: 1024
   http2:
      enabled: true
   port: 8023
   servlet:
      contextPath: /

spring:
   application:
      name: Quartz
   datasource:
      url: jdbc:mysql://localhost:3306/quartz_demo?useSSL=false&serverTimezone=Asia/Jakarta&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8
      username: root
      password:
      driverClassName: com.mysql.cj.jdbc.Driver
      max-active: 100
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-run-millis: 5000
      min-evictable-idle-time-millis: 6000
   jpa:
     properties:
        hibernate:
           database-platform: default
           show_sql: true
           use_sql_comments: false
           format_sql: true
     hibernate:
        ddlAuto: update
     #Without this sometimes ddl-auto not working in yml file, depends on version of springboot
     generate-ddl: true
   #MULTIPART (MultipartProperties)
   #Enable multipart uploads
   servlet:
      multipart:
         enabled: true
         #Max file size.
         max-file-size: 200MB
         max-request-size: 215MB
         file-size-threshold: 2KB
   #Quartz Properties
   quartz:
      job-store-type: jdbc
      properties:
         org:
            quartz:
               threadPool:
                  threadCount: 5
   #Mail Properties
   mail:
      host: smtp.gmail.com
      port: 587
      #Email sender
      username: your.email@gmail.com
      #Note that, Gmail’s SMTP access is disabled by default. To allow this app to send emails using your Gmail account
      #Go to https://myaccount.google.com/security?pli=1#connectedapps
      #Set ‘Allow less secure apps’ to YES
      #This sample password was generated by gmail based on your password email
      password: yjbpfxgjitwommnv
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  required: true
                  enabled: true
               ssl:
                  trust: smtp.gmail.com
               connectiontimeout: 5000
               timeout: 5000
               writetimeout: 5000
               socketFactory:
                  port: 465
                  class: javax.net.ssl.SSLSocketFactory
logging:
   file: logs/quartz.log
   pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
   level:
      org:
         springframework:
            security: DEBUG
            web: DEBUG
    #root: DEBUG
management:
   security:
      enabled: true
org:
   quartz:
      jobStore:
         driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate   